export const INDICATORS = [
  { label: "Active Day Entertainment", value: "active_day_entertainment" },
  { label: "Annual Revenue Estimate", value: "annual_reve_estimate" },
  {
    label: "Annual Revenue Estimate Lower",
    value: "annual_reve_estimate_lower",
  },
  {
    label: "Annual Revenue Estimate Upper",
    value: "annual_reve_estimate_upper",
  },
  { label: "Appetiser Price", value: "appetiser_price" },
  { label: "Area Adjectives", value: "area_adjectives" },
  { label: "Booking Rating", value: "booking_rating" },
  { label: "Chain ID", value: "chain_id" },
  { label: "Chain Name", value: "chain_name" },
  {
    label: "Consumer Engagement Growth Rank",
    value: "consumer_engagement_growth_rank",
  },
  {
    label: "Consumer Engagement Growth Rank Percentile",
    value: "consumer_engagement_growth_rank_perc",
  },
  { label: "Consumer Engagement Rank", value: "consumer_engagement_rank" },
  {
    label: "Consumer Engagement Rank Percentile",
    value: "consumer_engagement_rank_perc",
  },
  { label: "Consumer Rating Rank", value: "consumer_rating_rank" },
  { label: "Consumer Rating Score", value: "consumer_rating_score" },
  { label: "Country", value: "country" },
  { label: "Delivery", value: "delivery" },
  { label: "Dessert Price", value: "dessert_price" },
  {
    label: "Evening & Night Entertainment",
    value: "evening_night_entertainment",
  },
  { label: "Facility Highlights", value: "facility_highlights" },
  { label: "Food and Drink Facilities", value: "food_and_drink_facilities" },
  { label: "Food Beverage Rank", value: "food_beverage_rank" },
  { label: "Food Propositions", value: "food_propositions" },
  { label: "Google Place ID", value: "google_place_id" },
  { label: "Google Place Type", value: "google_place_type" },
  { label: "Government ID", value: "government_id" },
  { label: "Growth Segment", value: "growth_segment" },
  { label: "Has Bar", value: "has_bar" },
  { label: "Has Restaurant", value: "has_restaurant" },
  { label: "House Number", value: "house_number" },
  { label: "Inside Seating", value: "inside_seating" },
  { label: "Latitude", value: "latitude" },
  { label: "Local Market Rank", value: "local_market_rank" },
  { label: "Locality (City)", value: "locality" },
  { label: "Longitude", value: "longitude" },
  { label: "Main Course Price", value: "main_course_price" },
  { label: "Meal Types", value: "meal_types" },
  { label: "Newly Added", value: "newly_added" },
  { label: "Not Offered Tags", value: "not_offered_tags" },
  { label: "Number of HoReCa Outlets", value: "number_of_horeca_outlets" },
  { label: "Number of Rooms", value: "number_of_rooms" },
  { label: "Number of Stars", value: "number_of_stars" },
  { label: "Offered Tags", value: "offered_tags" },
  { label: "Offers Alcohol", value: "offers_alcohol" },
  { label: "Offers Beer", value: "offers_beer" },
  { label: "Offers Snacks/Small Meals", value: "offers_snacks_small_meals" },
  { label: "Offers Spirits", value: "offers_spirits" },
  { label: "Offers Takeaway Option", value: "offers_takeaway_option" },
  { label: "Offers Warm Meal", value: "offers_warm_meal" },
  { label: "Offers Wine", value: "offers_wine" },
  { label: "Outside Seating", value: "outside_seating" },
  { label: "Peak Day", value: "peak_day" },
  {
    label: "Peak Day to Median Day Percentage",
    value: "peak_day_to_median_day_percentage",
  },
  { label: "Peak Hours", value: "peak_hours" },
  {
    label: "Peak Hours to Median Hours Percentage",
    value: "peak_hours_to_median_hours_percentage",
  },
  { label: "Popular Facilities", value: "popular_facilities" },
  { label: "Postal Code", value: "postal_code" },
  { label: "Potential Beer", value: "potential_beer" },
  { label: "Potential Beverage", value: "potential_beverage" },
  { label: "Potential Coffee/Tea", value: "potential_coffee_tea" },
  { label: "Potential Cold Drinks", value: "potential_cold_drinks" },
  { label: "Potential Food", value: "potential_food" },
  { label: "Potential Spirits", value: "potential_spirits" },
  { label: "Potential Wine", value: "potential_wine" },
  { label: "Premise Address", value: "premise_address" },
  { label: "Premise Email", value: "premise_email" },
  { label: "Premise Name", value: "premise_name" },
  { label: "Premise Phone", value: "premise_phone" },
  { label: "Price Level", value: "price_level" },
  { label: "Price Level Bucket", value: "price_level_bucket" },
  { label: "Price Level Percentile", value: "price_level_percentile" },
  { label: "Price Level Source", value: "price_level_source" },
  { label: "Primary Segment", value: "primary_segment" },
  { label: "Primary Subsegment", value: "primary_subsegment" },
  { label: "Region 1", value: "region_1" },
  { label: "Region 2", value: "region_2" },
  { label: "Region 3", value: "region_3" },
  { label: "Review Topics", value: "review_topics" },
  { label: "Salad Price", value: "salad_price" },
  { label: "Second Peak Day", value: "second_peak_day" },
  {
    label: "Second Peak Day to Median Day Percentage",
    value: "second_peak_day_to_median_day_percentage",
  },
  { label: "Second Peak Hours", value: "second_peak_hours" },
  {
    label: "Second Peak Hours to Median Hours Percentage",
    value: "second_peak_hours_to_median_hours_percentage",
  },
  { label: "Serves Cocktails", value: "serves_cocktails" },
  { label: "Serves Coffee", value: "serves_coffee" },
  { label: "SharpGrid ID", value: "sharpgrid_id" },
  { label: "Side Dish Price", value: "side_dish_price" },
  { label: "Soup Price", value: "soup_price" },
  { label: "Source Data Period", value: "source_data_period" },
  { label: "Standard Room Cost", value: "standard_room_cost" },
  { label: "Status", value: "status" },
  { label: "Status Change Time", value: "status_change_time" },
  { label: "Street", value: "street" },
  { label: "Title Picture URL", value: "title_picture_url" },
  { label: "Update Label", value: "update_label" },
  { label: "Update Period", value: "update_period" },
  { label: "Upload Batch ID", value: "upload_batch_id" },
  { label: "Via Michelin", value: "via_michelin" },
  { label: "Week Opening Hours Segment", value: "week_opening_hours_segment" },
  { label: "Weekdays Opened", value: "weekdays_opened" },
];

export const COUNTRIES = [
  { label: "🇦🇱 Albania", value: "AL" },
  { label: "🇦🇪 United Arab Emirates", value: "AE" },
  { label: "🇦🇩 Andorra", value: "AD" },
  { label: "🇦🇹 Austria", value: "AT" },
  { label: "🇧🇪 Belgium", value: "BE" },
  { label: "🇧🇦 Bosnia and Herzegovina", value: "BA" },
  { label: "🇧🇬 Bulgaria", value: "BG" },
  { label: "🇭🇷 Croatia", value: "HR" },
  { label: "🇨🇾 Cyprus", value: "CY" },
  { label: "🇨🇿 Czech Republic", value: "CZ" },
  { label: "🇩🇰 Denmark", value: "DK" },
  { label: "🇪🇪 Estonia", value: "EE" },
  { label: "🇫🇮 Finland", value: "FI" },
  { label: "🇫🇷 France", value: "FR" },
  { label: "🇩🇪 Germany", value: "DE" },
  { label: "🇬🇷 Greece", value: "GR" },
  { label: "🇭🇺 Hungary", value: "HU" },
  { label: "🇮🇪 Ireland", value: "IE" },
  { label: "🇮🇹 Italy", value: "IT" },
  { label: "🇽🇰 Kosovo", value: "XK" },
  { label: "🇱🇻 Latvia", value: "LV" },
  { label: "🇱🇮 Liechtenstein", value: "LI" },
  { label: "🇱🇹 Lithuania", value: "LT" },
  { label: "🇱🇺 Luxembourg", value: "LU" },
  { label: "🇲🇹 Malta", value: "MT" },
  { label: "🇲🇪 Montenegro", value: "ME" },
  { label: "🇳🇱 Netherlands", value: "NL" },
  { label: "🇲🇰 North Macedonia", value: "MK" },
  { label: "🇳🇴 Norway", value: "NO" },
  { label: "🇵🇱 Poland", value: "PL" },
  { label: "🇵🇹 Portugal", value: "PT" },
  { label: "🇷🇴 Romania", value: "RO" },
  { label: "🇸🇲 San Marino", value: "SM" },
  { label: "🇷🇸 Serbia", value: "RS" },
  { label: "🇸🇰 Slovakia", value: "SK" },
  { label: "🇸🇮 Slovenia", value: "SI" },
  { label: "🇪🇸 Spain", value: "ES" },
  { label: "🇸🇪 Sweden", value: "SE" },
  { label: "🇨🇭 Switzerland", value: "CH" },
  { label: "🇹🇷 Turkey", value: "TR" },
  { label: "🇬🇧 United Kingdom", value: "GB" },
];
